// src/constants/genres.js
export const GENRE_OPTIONS = [
  { value: 'Ação',               key: 'action',      emoji: '💥' },
  { value: 'Aventura',           key: 'adventure',   emoji: '🗺️' },
  { value: 'Comédia',            key: 'comedy',      emoji: '😂' },
  { value: 'Drama',              key: 'drama',       emoji: '🎭' },
  { value: 'Fantasia',           key: 'fantasy',     emoji: '🧙' },
  { value: 'Ficção Científica',  key: 'scifi',       emoji: '🚀' },
  { value: 'Terror',             key: 'horror',      emoji: '👻' },
  { value: 'Mistério',           key: 'mystery',     emoji: '🔍' },
  { value: 'Suspense / Thriller',key: 'thriller',    emoji: '😰' },
  { value: 'Romance',            key: 'romance',     emoji: '❤️' },
  { value: 'Crime / Policial',   key: 'crime',       emoji: '🕵️' },
  { value: 'Guerra',             key: 'war',         emoji: '⚔️' },
  { value: 'Western',            key: 'western',     emoji: '🤠' },
  { value: 'Histórico / Épico',  key: 'historical',  emoji: '🏛️' },
  { value: 'Musical',            key: 'musical',     emoji: '🎵' },
  { value: 'Animação',           key: 'animation',   emoji: '✨' },
  { value: 'Documentário',       key: 'documentary', emoji: '📽️' },
  { value: 'Família / Infantil', key: 'family',      emoji: '👨‍👩‍👧' },
  { value: 'Biografia',          key: 'biography',   emoji: '📖' },
  { value: 'Esporte',            key: 'sports',      emoji: '🏆' },
]
