"""add_language_to_profiles

Revision ID: 1e6ef11f610f
Revises: fca41f860268
Create Date: 2026-03-10 20:22:40.702820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6ef11f610f'
down_revision: Union[str, None] = 'fca41f860268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns WHERE table_name='profiles' AND column_name='language'"
    ))
    if result.fetchone() is None:
        op.add_column('profiles', sa.Column('language', sa.String(), server_default='pt', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'language')
    # ### end Alembic commands ###
