"""fix_streaming_platforms_not_null

Revision ID: 4b826e2a51a7
Revises: 898b520122b1
Create Date: 2026-03-10 22:17:37.406808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b826e2a51a7'
down_revision: Union[str, None] = '898b520122b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE profiles SET streaming_platforms = '{}' WHERE streaming_platforms IS NULL")
    op.alter_column('profiles', 'streaming_platforms',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'streaming_platforms',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###
