"""add_streaming_platforms_to_profiles

Revision ID: 898b520122b1
Revises: 1e6ef11f610f
Create Date: 2026-03-10 22:14:51.333174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898b520122b1'
down_revision: Union[str, None] = '1e6ef11f610f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('streaming_platforms', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'streaming_platforms')
    # ### end Alembic commands ###
