"""add_email_verified_and_verification_tokens

Revision ID: 9fc8046827f8
Revises: 4b826e2a51a7
Create Date: 2026-03-13 22:57:24.542469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fc8046827f8'
down_revision: Union[str, None] = '4b826e2a51a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # Create email_verification_tokens only if it doesn't exist
    result = conn.execute(sa.text(
        "SELECT table_name FROM information_schema.tables WHERE table_name='email_verification_tokens'"
    ))
    if result.fetchone() is None:
        op.create_table('email_verification_tokens',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.UUID(), nullable=False),
            sa.Column('token', sa.String(length=64), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('used_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)

    # Drop old indexes only if they exist
    result = conn.execute(sa.text(
        "SELECT indexname FROM pg_indexes WHERE indexname='idx_reset_tokens_token'"
    ))
    if result.fetchone() is not None:
        op.drop_index('idx_reset_tokens_token', table_name='password_reset_tokens')

    result = conn.execute(sa.text(
        "SELECT indexname FROM pg_indexes WHERE indexname='idx_reset_tokens_user_id'"
    ))
    if result.fetchone() is not None:
        op.drop_index('idx_reset_tokens_user_id', table_name='password_reset_tokens')

    op.alter_column('recommendations', 'prompt_used',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('recommendations', 'response',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_unique_constraint(None, 'recommendations', ['user_id'])

    # Drop FK only if it exists
    result = conn.execute(sa.text(
        "SELECT constraint_name FROM information_schema.table_constraints "
        "WHERE table_name='recommendations' AND constraint_name='recommendations_user_id_fkey'"
    ))
    if result.fetchone() is not None:
        op.drop_constraint('recommendations_user_id_fkey', 'recommendations', type_='foreignkey')

    op.create_foreign_key(None, 'recommendations', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # Add email_verified columns only if they don't exist
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns WHERE table_name='users' AND column_name='email_verified'"
    ))
    if result.fetchone() is None:
        op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns WHERE table_name='users' AND column_name='email_verified_at'"
    ))
    if result.fetchone() is None:
        op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.create_foreign_key('recommendations_user_id_fkey', 'recommendations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'recommendations', type_='unique')
    op.alter_column('recommendations', 'response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('recommendations', 'prompt_used',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.create_index('idx_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('idx_reset_tokens_token', 'password_reset_tokens', ['token'], unique=False)
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
