"""initial tables

Revision ID: f8bc987ed51e
Revises: a3f92c1d0e47
Create Date: 2026-03-15 10:47:52.810195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bc987ed51e'
down_revision: Union[str, None] = 'a3f92c1d0e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('language', sa.String(length=8), server_default='pt', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'language')
    # ### end Alembic commands ###
